id: P009419
initial_creation_type: ocr
source_metadata:
  id: bdr:W2DB5974
  title: རོང་ཆེན་ལྗགས་ནག་པ་ཀི་རྟི་སྐུ་འཕྲེང་རིམ་བྱོན་གྱི་རྣམ་ཐར་ཕྱོགས་བསྒྲིགས
  author: ''
  volumes:
    ce36b9f7c6ac4e1fa9bc78c95cc25cbb:
      image_group_id: I1PD27500
      title: ''
      volume_number: 1
      total_pages: 840
      base_file: v001.txt
    8bd5046c88ff4d14835cad328c8a2883:
      image_group_id: I1PD27501
      title: ''
      volume_number: 2
      total_pages: 696
      base_file: v002.txt
